# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  # batch: true
  branches:
    include:
      - upstream
  tags:
    include:
      - '*'

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'd32f9265-829e-4083-98cf-d4b23563713d'
  nginxImageRepository: 'bergendahls-nginx'
  controllerImageRepository: 'bergendahls-nginx-ingress'
  containerRegistry: 'bfoecomcontainer.azurecr.io'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Bash@3
            displayName: Build and push nginx image
            inputs:
              targetType: 'inline'
              script: cd images/nginx && make push
            env:
              MYSECRET: $(Foo)
          # - task: Docker@2
          #   displayName: Build and push an image to container registry
          #   inputs:
          #     command: buildAndPush
          #     repository: $(imageRepository)
          #     dockerfile: $(dockerfilePath)
          #     containerRegistry: $(dockerRegistryServiceConnection)
          #     tags: |
          #       $(tag)